name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: npm install
      
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: anthonyjhoiro6/surfer-du-web-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
